version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: sergeilebedev/backend:latest
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: sergeilebedev/frontend:latest
    volumes:
      - static_value:/frontend/build/static/
      - build:/frontend/build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - build:/usr/share/nginx/html/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  build:

